---
- name: Installl apache
  hosts: test
  become: true
  become_user: root
  vars:
   web_pkg: httpd
   firewall_pkg: firewalld
   web_service: httpd
   firewall_service: firewalld
   perl_pkg: perl
   rule: httpd
  tasks:
  - name : Installl the required packages
    yum: 
     name: 
      - "{{ web_pkg }}"
      - "{{ firewall_pkg }}"
      - "{{ perl_pkg }}"
     state: latest
  - name: Start and enable the {{ firewall_service }}    
    service:
     name: "{{ firewall_service }}"
     enabled: true
     state: started
  - name: Start and enable the  {{ web_service }}        
    service:
     name: "{{ web_service }}"
     enabled: true
     state: started
  - name: Create the web contet
    copy:
     content: "Hello this iswebserver"
     dest: /var/www/html/index.html

 # - name: open the port {{ rule }}
 #   firewalld:
 #    service: "{{ rule }}"
 #    permanent: true
 #    immediate: true
 #    state: enabled
